In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.cross_decomposition import PLSRegression

In [60]:
housPrice_df = pd.read_csv('MELBOURNE_HOUSE_PRICES_LESS.csv')
housPrice_df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
5,Airport West,4/32 Earl St,2,t,530000.0,S,Jellis,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
6,Airport West,3/74 Hawker St,2,u,540000.0,S,Barry,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
7,Airport West,1/26 Highridge Cr,3,h,715000.0,SP,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
8,Albanvale,1 Jackson Cct,6,h,NaN,PI,hockingstuart,1/04/2017,3021,Western Metropolitan,1899,14.0,Brimbank City Council
9,Albert Park,18 Mills St,3,h,1925000.0,S,Cayzer,1/04/2017,3206,Southern Metropolitan,3280,3.0,Port Phillip City Council
10,Albion,3/15 Drummartin St,3,u,515000.0,S,Douglas,1/04/2017,3020,Western Metropolitan,2185,10.5,Brimbank City Council
11,Albion,3A Kororoit St,4,h,717000.0,S,Bells,1/04/2017,3020,Western Metropolitan,2185,10.5,Brimbank City Council
12,Alphington,55 Fulham Rd,2,h,1675000.0,S,Miles,1/04/2017,3078,Northern Metropolitan,2211,5.7,Darebin City Council
13,Alphington,41 Toolangi Rd,4,h,2008000.0,S,Jellis,1/04/2017,3078,Northern Metropolitan,2211,5.7,Darebin City Council
14,Altona,9 Delmont Av,2,h,860000.0,SP,Barlow,1/04/2017,3018,Western Metropolitan,5301,11.0,Hobsons Bay City Council
15,Altona Meadows,57 Tatman Dr,4,h,NaN,SN,Barry,1/04/2017,3028,Western Metropolitan,7630,15.5,Hobsons Bay City Council
16,Altona North,14 Seventh Av,3,h,720000.0,S,Hunter,1/04/2017,3025,Western Metropolitan,5132,9.4,Hobsons Bay City Council
17,Armadale,2/23 Ashleigh Rd,2,u,836000.0,S,Jellis,1/04/2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
18,Armadale,6A Auburn Gr,2,h,2110000.0,S,Jellis,1/04/2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
19,Armadale,746 High St,3,h,1386000.0,S,Marshall,1/04/2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
20,Armadale,14/25 Kooyong Rd,2,u,580000.0,VB,hockingstuart,1/04/2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
21,Armadale,6/38 Wattletree Rd,1,u,355000.0,S,hockingstuart,1/04/2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
22,Ascot Vale,8 The Grove,3,h,1123100.0,S,Ray,1/04/2017,3032,Western Metropolitan,6567,4.3,Moonee Valley City Council
23,Ashburton,1/48 Karnak Rd,3,u,1270000.0,S,Fletchers,1/04/2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
24,Ashburton,1 Pitt St,4,h,NaN,S,Jellis,1/04/2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
25,Ashburton,61A Victory Bvd,3,t,1610000.0,S,Jellis,1/04/2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
26,Ashwood,43 Douglas St,4,h,1435000.0,S,Ray,1/04/2017,3147,Southern Metropolitan,2894,10.2,Monash City Council
27,Aspendale,4 Jirrah Ct,4,h,1431000.0,S,hockingstuart,1/04/2017,3195,South-Eastern Metropolitan,2824,21.5,Kingston City Council
28,Aspendale Gardens,8 Mangrove Ct,4,h,996000.0,S,Ray,1/04/2017,3195,South-Eastern Metropolitan,2243,21.5,Kingston City Council
29,Attwood,46 Threadneedle St,4,h,NaN,SN,Barry,1/04/2017,3049,Northern Metropolitan,1130,16.5,Hume City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60642,Windsor,68 Hornby St,2,h,1000000.0,VB,Beller,30/12/2017,3181,Southern Metropolitan,4380,4.6,Port Phillip City Council
60643,Wollert,66 Fulham Wy,3,h,640000.0,S,HAR,30/12/2017,3750,Northern Metropolitan,2940,25.5,Whittlesea City Council
60644,Wollert,11 Tindales Rd,4,h,520600.0,S,Stockdale,30/12/2017,3750,Northern Metropolitan,2940,25.5,Whittlesea City Council
60645,Wonga Park,16 Fulford Rd,3,h,NaN,PI,Jellis,30/12/2017,3115,Eastern Victoria,1328,25.2,Manningham City Council
60646,Wyndham Vale,5 Chatswood Pl,3,h,410000.0,S,hockingstuart,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
60647,Wyndham Vale,21 Mermaid Cr,3,h,400000.0,SP,Barry,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
60648,Wyndham Vale,20 Olive Wy,5,h,NaN,VB,Greg,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
60649,Wyndham Vale,8 Opala Ct,3,h,416000.0,S,Sweeney,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
60650,Wyndham Vale,15 Yaltara Dr,3,h,NaN,S,hockingstuart,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
60651,Yallambie,7/6 Borlase St,3,t,745000.0,S,Buckingham,30/12/2017,3085,Northern Metropolitan,1369,12.7,Banyule City Council
60652,Yallambie,8/6 Borlase St,3,t,655000.0,S,Buckingham,30/12/2017,3085,Northern Metropolitan,1369,12.7,Banyule City Council
60653,Yarraville,9 Alice St,2,h,870000.0,SP,Jas,30/12/2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
60654,Yarraville,4/119 Gamon St,2,u,495000.0,SP,Village,30/12/2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
60655,Yarraville,26 Grace St,3,h,1000000.0,SP,Jas,30/12/2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
60656,Yarraville,2/13 Stephen St,2,u,410000.0,SP,Sweeney,30/12/2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
60657,Yarraville,4/247 Williamstown Rd,3,t,NaN,S,Jas,30/12/2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
60658,Bayswater,62 Phyllis St,3,h,736000.0,SP,Biggin,31/03/2018,3153,Eastern Metropolitan,5030,23.2,Knox City Council
60659,Burwood,29 Summit Rd,4,h,NaN,PN,@Realty,31/03/2018,3125,Southern Metropolitan,5678,10.4,Monash City Council
60660,Doveton,12 Scarlet Dr,3,h,595000.0,PI,REMAX,31/03/2018,3177,South-Eastern Metropolitan,3533,28.8,Casey City Council
60661,Frankston,5/33 Dandenong East Rd,2,u,375000.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
60662,Frankston,7 Ince Ct,5,h,710000.0,PI,hockingstuart,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
60663,Frankston,1/34 Petrie St,2,u,345000.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
60664,Frankston,3/34 Petrie St,2,u,340000.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
60665,Frankston,4/34 Petrie St,2,u,347700.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
60666,Preston,229 Murray Rd,3,h,808000.0,S,RW,31/03/2018,3072,Northern Metropolitan,14577,8.4,Darebin City Council
60667,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
60668,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
60669,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
60670,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
60671,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [17]:
housPrice_df = housPrice_df.drop(['Address', 'SellerG', 'Date', 'CouncilArea'], 1)
lables = housPrice_df.columns[:]
lables

Index(['Suburb', 'Rooms', 'Type', 'Price', 'Method', 'Postcode', 'Regionname',
       'Propertycount', 'Distance'],
      dtype='object')

In [25]:
Method = pd.get_dummies(housPrice_df['Method'])
Method.head()

   PI  PN  S  SA  SN  SP  SS  VB  W
0   0   0  1   0   0   0   0   0  0
1   0   0  1   0   0   0   0   0  0
2   0   0  1   0   0   0   0   0  0
3   0   0  1   0   0   0   0   0  0
4   0   0  1   0   0   0   0   0  0

In [27]:
houseType = pd.get_dummies(housPrice_df['Type'])
houseType.head()

   h  t  u
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

In [22]:
Suburb = pd.get_dummies(housPrice_df['Suburb'])
Suburb.head()

,Abbotsford,Aberfeldie,Airport West,Albanvale,Albert Park,Albion,Alphington,Altona,Altona Meadows,Altona North,...,Woori Yallock,Wyndham Vale,Yallambie,Yan Yean,Yarra Glen,Yarra Junction,Yarrambat,Yarraville,croydon,viewbank
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
Regionname = pd.get_dummies(housPrice_df['Regionname'])
Regionname.head()

,Eastern Metropolitan,Eastern Victoria,Northern Metropolitan,Northern Victoria,South-Eastern Metropolitan,Southern Metropolitan,Western Metropolitan,Western Victoria
0,0,0,1,0,0,0,0,0
1,0,0,1,0,0,0,0,0
2,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,1,0

In [48]:
housPrice_df['Price'] = np.log(housPrice_df['Price'])
housPrice_df = pd.concat([housPrice_df, Suburb, Method, houseType, Regionname], axis=1).drop(['Type', 'Method', 'Suburb', 'Regionname'], 1).dropna()
housPrice_df = housPrice_df.drop([53116, 57390])
housPrice_df.head()

,Rooms,Price,Postcode,Propertycount,Distance,Abbotsford,Aberfeldie,Airport West,Albanvale,Albert Park,...,t,u,Eastern Metropolitan,Eastern Victoria,Northern Metropolitan,Northern Victoria,South-Eastern Metropolitan,Southern Metropolitan,Western Metropolitan,Western Victoria
0,3.0,2.654248,3067.0,4019.0,3.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,3.0,2.640083,3067.0,4019.0,3.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3.0,2.650857,3067.0,4019.0,3.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,3.0,2.655417,3040.0,1543.0,7.5,0.0,1.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,2.0,2.596376,3042.0,3464.0,10.4,0.0,0.0,1.0,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [51]:
X = housPrice_df.drop('Price', 1)
y = housPrice_df['Price']

In [54]:
# Instantiate and fit our model.
regr = linear_model.LinearRegression()

regr.fit(X, y)

# Inspect the results.
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, y))

Coefficients:
 [  1.50576556e-02   4.33584869e+02  -5.22292823e+00 ...,   2.01294997e+05
   5.40952310e+05   5.45215360e+04]

Intercept:
 -11126976.4313

R-squared:
0.761985924743

In [55]:
cross_val_score(regr, X, y, cv=10)

array([ -7.52448818e+11,  -1.44594183e+11,  -7.88403927e+08,
        -8.74473903e+08,  -5.84702735e+10,  -1.18689282e+10,
        -2.39811626e+11,  -3.37616691e+12,  -2.54073216e+11,
        -4.21152931e+10])

# Partial Least Squares Regression

In [56]:
# Fit a linear model using Partial Least Squares Regression.
# Reduce feature space to 9 dimensions.
pls1 = PLSRegression(n_components=9)

# Reduce X to R(X) and regress on y.
pls1.fit(X, y)

# Save predicted values.
Y_PLS_pred = pls1.predict(X)
print('R-squared PLSR:', pls1.score(X, y))

R-squared PLSR: 0.761985895603

In [57]:
cross_val_score(pls1, X, y, cv=5)

array([ 0.75472749,  0.76224066,  0.75784627,  0.75980106,  0.75154614])

# lasso